project:
  type: website
  resources:
    - google*.html
    - slides/**

website:
  title: "Diego Berti"
  site-url: "https://diegoberti.github.io"
  description: "Academic website of Diego Berti, researcher in Mathematical Analysis, partial differential equations, dynamical systems, and mathematical physics."
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Publications
        href: publications.qmd
      - text: Academic Bio
        href: short CV.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Talks & Seminars
        href: talks&seminars.qmd
    search: false
  
  
  # sidebar:
  #   style: "docked"
  #   search: false
  #   contents:
  #     - href: index.qmd
  #       text: Home
  #     - href: publications.qmd
  #       text: Publications  
  #     - href: short CV.qmd
  #       text: Academic Bio
  #     - href: teaching.qmd
  #       text: Teaching
  #     - href: talks&seminars.qmd
  #       text: Talks & Seminars
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false
    