project:
  type: website
  resources:
    - google*.html
    - slides/**

website:
  title: "Diego Berti"
  site-url: "https://diegoberti.github.io"
  description: "Academic website of Diego Berti, researcher in Mathematical Analysis, partial differential equations, dynamical systems, and mathematical physics."
  sidebar:
    style: "docked"
    search: false
    contents:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications  
      - href: short CV.qmd
        text: Academic Bio
      - href: teaching.qmd
        text: Teaching
      - href: talks&seminars.qmd
        text: Talks & Seminars
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false
    