---
title: "Teaching"
---

- *Esercitazioni di Analisi Matematica 2*, Corso di Laurea Triennale in Matematica per la Finanza e l'Assicurazione, Università degli Studi di Torino, 32 hours, 4 CFU, a.a. 2025/26.

- *Esercitazioni di Analisi Matematica 2*, Corso di Laurea Triennale in Matematica per la Finanza e l'Assicurazione, Università degli Studi di Torino, 32 hours, 4 CFU, a.a. 2024/25.

- *Matematica e Statistica*, Corso di Laurea Magistrale a Ciclo Unico in Chimica e Tecnologia del Farmaco, Università degli Studi di Torino, 32 hours, 2 CFU, a.a. 2024/25.

- *Esercitazioni di Analisi Matematica 2*, Corso di Laurea Triennale in Matematica per la Finanza e l'Assicurazione, Università degli Studi di Torino, 32 hours, 4 CFU, a.a. 2023/24.

- *Matematica e Statistica*, Corso di Laurea Magistrale a Ciclo Unico in Chimica e Tecnologia del Farmaco, Università degli Studi di Torino, 32 hours, 2 CFU, a.a. 2023/24.

- *Elementi di Matematica (A–K)*, Corso di Laurea in Biotecnologie, Università degli Studi di Firenze, 24 hours, 3 CFU, a.a. 2022/23.

- *Esercitazioni – Analisi Matematica A (L–Z)*, Corso di Laurea in Ingegneria Meccatronica, Università degli Studi di Modena e Reggio Emilia, 27 hours, 3 CFU, a.a. 2022/23.

- *Analisi Matematica II*, Corso di Laurea in Ingegneria Biomedica, Università degli Studi di Firenze, 18 hours, 2 CFU, a.a. 2021/22.

- *Elementi di Matematica (L–Z)*, Corso di Laurea in Biotecnologie, Università degli Studi di Firenze, 24 hours, 3 CFU, a.a. 2021/22.

- *Elementi di Matematica (A–K)*, Corso di Laurea in Biotecnologie, Università degli Studi di Firenze, 24 hours, 3 CFU, a.a. 2021/22.

- *Esercitazioni – Analisi Matematica A (L–Z)*, Corso di Laurea in Ingegneria Meccatronica, Università degli Studi di Modena e Reggio Emilia, 27 hours, 3 CFU, a.a. 2021/22.

- *Esercitazioni – Analisi Matematica A (L–Z)*, Corso di Laurea in Ingegneria Meccatronica, Università degli Studi di Modena e Reggio Emilia, 27 hours, 3 CFU, a.a. 2020/21.

- *Corso di Recupero OFA in Matematica*, Dipartimento di Scienze e Tecnologie Agrarie, Alimentari e Forestali, Università degli Studi di Firenze, 24 hours, a.a. 2019/20.

- Tutor for *Matematica e Esercitazioni*, Corso di Laurea in Scienze Geologiche, Università degli Studi di Firenze, a.a. 2016/17.